apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerfile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerfile
  template:
    metadata:
      labels:
        app: dockerfile
    spec:
      containers:
      - name: NTI-Test
        image: mostafayounis0/dockerfile
        ports:
        - containerPort: 5000
